/**
 * @file generators/moodle.ts
 * @description Generates global Moodle context markdown files.
 *
 * Improvements over initial version:
 *   - findPluginDirs uses glob correctly (no invalid depth option)
 *   - findAllPlugins helper removed (was unused and broken)
 *   - All generated paths are relative to moodlePath
 *   - Each generator wrapped in try/catch error boundary
 *   - Cache integration via globalCache (skips unchanged files)
 *   - generate_ctags implemented via child_process when ctags is available
 *   - All output messages in English
 */

import { writeFileSync, existsSync }   from "fs";
import { join, relative }              from "path";
import { glob }                        from "glob";
import { execSync }                    from "child_process";

import { extractMoodleApi }                                                   from "../extractors/api.js";
import { parseEventsPhp }                                                     from "../extractors/events.js";
import { parseTasksPhp, formatCronSchedule }                                  from "../extractors/tasks.js";
import { parseServicesPhp }                                                   from "../extractors/services.js";
import { parseInstallXml }                                                    from "../extractors/schema.js";
import { extractClasses }                                                     from "../extractors/classes.js";
import { parseAccessPhp }                                                     from "../extractors/capabilities.js";
import { detectPlugin }                                                       from "../extractors/plugin.js";
import { globalCache, getMoodleSourcePatterns }                               from "../cache.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GeneratorResult {
  file:    string;
  success: boolean;
  error?:  string;
  skipped?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function write(filePath: string, content: string): GeneratorResult {
  try {
    writeFileSync(filePath, content, "utf-8");
    globalCache.mark(filePath);
    return { file: filePath, success: true };
  } catch (e) {
    return { file: filePath, success: false, error: String(e) };
  }
}

function timestamp(): string {
  return new Date().toISOString().replace("T", " ").substring(0, 19);
}

function header(title: string, description: string): string {
  return [
    `# ${title}`,
    "",
    `> ${description}`,
    "",
    `_Generated by moodle-mcp on ${timestamp()}_`,
    "",
    "---",
    "",
  ].join("\n");
}

/**
 * Wraps a generator function with an error boundary.
 * Returns a failed GeneratorResult instead of throwing.
 */
async function safely(
  outputFile: string,
  fn: () => Promise<GeneratorResult>
): Promise<GeneratorResult> {
  try {
    return await fn();
  } catch (e) {
    return { file: outputFile, success: false, error: String(e) };
  }
}

/**
 * Finds plugin directories by scanning for version.php exactly 2 levels deep.
 * Uses two glob passes to avoid the invalid 'depth' option bug.
 */
async function findPluginDirs(moodlePath: string): Promise<string[]> {
  const files = await glob("*/*/version.php", {
    cwd:      moodlePath,
    absolute: true,
    ignore:   ["vendor/**", "node_modules/**", "lib/**"],
  });

  return [...new Set(
    files.map((f) => f.replace(/\/version\.php$/, ""))
  )];
}

// ---------------------------------------------------------------------------
// Individual generators
// ---------------------------------------------------------------------------

export async function generateAiContext(
  moodlePath: string,
  moodleVersion: string
): Promise<GeneratorResult> {
  const output = join(moodlePath, "AI_CONTEXT.md");

  return safely(output, async () => {
    const pluginDirs  = await findPluginDirs(moodlePath);

    const content = [
      header("Moodle AI Context", "High-level overview of this Moodle installation for AI assistants."),
      "## Installation",
      "",
      "| Property | Value |",
      "|----------|-------|",
      `| Version  | ${moodleVersion} |`,
      `| Path     | ${moodlePath} |`,
      `| Plugins  | ${pluginDirs.length} detected |`,
      "",
      "---",
      "",
      "## Directory Structure",
      "",
      "| Directory | Purpose |",
      "|-----------|---------|",
      "| `admin/`    | Administration tools and settings |",
      "| `auth/`     | Authentication plugins |",
      "| `blocks/`   | Block plugins |",
      "| `cache/`    | Moodle Universal Cache (MUC) |",
      "| `course/`   | Course formats and related |",
      "| `enrol/`    | Enrolment plugins |",
      "| `filter/`   | Text filter plugins |",
      "| `grade/`    | Grading system |",
      "| `lib/`      | Core Moodle APIs |",
      "| `local/`    | Local plugins |",
      "| `mod/`      | Activity modules |",
      "| `question/` | Question types |",
      "| `report/`   | Report plugins |",
      "| `theme/`    | Themes |",
      "| `user/`     | User management |",
      "",
      "---",
      "",
      "## Key APIs (lib/)",
      "",
      "| File | Purpose |",
      "|------|---------|",
      "| `accesslib.php`    | Capabilities, roles, contexts |",
      "| `moodlelib.php`    | Core utility functions |",
      "| `filelib.php`      | File API |",
      "| `weblib.php`       | Output and web utilities |",
      "| `gradelib.php`     | Grade API |",
      "| `completionlib.php`| Course completion |",
      "| `enrollib.php`     | Enrolment API |",
      "| `grouplib.php`     | Group API |",
      "| `externallib.php`  | Web services base |",
      "",
      "---",
      "",
      "## Coding Guidelines",
      "",
      "- Follow [Moodle Coding Style](https://docs.moodle.org/dev/Coding_style)",
      "- Use Moodle DB API (`$DB`) — avoid raw SQL when possible",
      "- Always call `require_login()` on pages requiring authentication",
      "- Validate parameters with `required_param()` / `optional_param()`",
      "- Use `$OUTPUT` for HTML rendering, never echo raw HTML in controllers",
      "- Capabilities must be checked with `require_capability()` or `has_capability()`",
      "- All user-supplied data must be escaped before output",
      "",
      "---",
      "",
      "## Index Files",
      "",
      "| File | Contents |",
      "|------|----------|",
      "| [MOODLE_AI_INDEX.md](MOODLE_AI_INDEX.md)               | Master index |",
      "| [MOODLE_AI_WORKSPACE.md](MOODLE_AI_WORKSPACE.md)       | AI workspace config |",
      "| [MOODLE_API_INDEX.md](MOODLE_API_INDEX.md)             | Core API functions |",
      "| [MOODLE_EVENTS_INDEX.md](MOODLE_EVENTS_INDEX.md)       | Event observers |",
      "| [MOODLE_TASKS_INDEX.md](MOODLE_TASKS_INDEX.md)         | Scheduled tasks |",
      "| [MOODLE_SERVICES_INDEX.md](MOODLE_SERVICES_INDEX.md)   | Web services |",
      "| [MOODLE_DB_TABLES_INDEX.md](MOODLE_DB_TABLES_INDEX.md) | Database tables |",
      "| [MOODLE_CLASSES_INDEX.md](MOODLE_CLASSES_INDEX.md)     | PHP classes |",
      "| [MOODLE_CAPABILITIES_INDEX.md](MOODLE_CAPABILITIES_INDEX.md) | Capabilities |",
      "| [MOODLE_PLUGIN_INDEX.md](MOODLE_PLUGIN_INDEX.md)       | Plugin map |",
      "",
    ].join("\n");

    return write(output, content);
  });
}

export function generateApiIndex(moodlePath: string): GeneratorResult {
  const output = join(moodlePath, "MOODLE_API_INDEX.md");

  try {
    const extraction = extractMoodleApi(moodlePath);
    const { counts }  = extraction;

    // Group by source file
    const byFile: Record<string, typeof extraction.functions> = {};
    for (const fn of extraction.functions) {
      if (!byFile[fn.file]) byFile[fn.file] = [];
      byFile[fn.file].push(fn);
    }

    const lines: string[] = [
      header(
        "Moodle API Index",
        "Public and deprecated functions extracted from Moodle's lib/ directory. " +
        "Private, internal, and undocumented functions are excluded."
      ),
      "## Summary",
      "",
      "| Visibility | Count |",
      "|------------|-------|",
      `| ✔ public     | ${counts.public} |`,
      `| ⚠ deprecated | ${counts.deprecated} |`,
      `| — internal   | ${counts.internal} (excluded) |`,
      `| — private    | ${counts.private} (excluded) |`,
      `| ? unverified | ${counts.unverified} (excluded) |`,
      "",
      `**Shown in this index: ${extraction.functions.length} functions**`,
      "",
      "---",
      "",
    ];

    for (const [file, fns] of Object.entries(byFile)) {
      lines.push(`## ${file}`, "");

      for (const fn of fns) {
        const summary    = fn.doc?.summary   ? ` — ${fn.doc.summary}`   : "";
        const returns    = fn.doc?.returns   ? ` → \`${fn.doc.returns}\`` : "";
        const since      = fn.doc?.since     ? ` _(since ${fn.doc.since})_` : "";
        const deprLabel  = fn.visibility === "deprecated"
          ? ` ~~**@deprecated**${fn.doc?.deprecated && fn.doc.deprecated !== "yes" ? `: ${fn.doc.deprecated}` : ""}~~`
          : "";

        lines.push(`- \`${fn.name}()\`${deprLabel}${summary}${returns}${since}`);
      }

      lines.push("");
    }

    return write(output, lines.join("\n"));
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

export async function generateEventsIndex(moodlePath: string): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_EVENTS_INDEX.md");

  return safely(output, async () => {
    const files = await glob("**/db/events.php", {
      cwd: moodlePath, absolute: true,
      ignore: ["vendor/**", "node_modules/**"],
    });

    const allEvents: Array<{ eventname: string; callback: string; source: string }> = [];

    for (const file of files) {
      try {
        const extraction = parseEventsPhp(file);
        if (!extraction) continue;
        const source = relative(moodlePath, file);
        for (const obs of extraction.observers) {
          allEvents.push({ eventname: obs.eventname, callback: obs.callback, source });
        }
      } catch { /* skip malformed file */ }
    }

    allEvents.sort((a, b) => a.eventname.localeCompare(b.eventname));

    const lines = [
      header("Moodle Events Index", "All event observers registered across all plugins."),
      `Sources scanned: **${files.length}** events.php files`,
      "",
      "---",
      "",
      "| Event | Callback | Source |",
      "|-------|----------|--------|",
      ...allEvents.map((e) => `| \`${e.eventname}\` | \`${e.callback}\` | ${e.source} |`),
      "",
    ];

    return write(output, lines.join("\n"));
  });
}

export async function generateTasksIndex(moodlePath: string): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_TASKS_INDEX.md");

  return safely(output, async () => {
    const files = await glob("**/db/tasks.php", {
      cwd: moodlePath, absolute: true,
      ignore: ["vendor/**", "node_modules/**"],
    });

    const lines = [
      header("Moodle Tasks Index", "All scheduled tasks registered across all plugins."),
      `Sources scanned: **${files.length}** tasks.php files`,
      "",
      "---",
      "",
      "| Class | Schedule | Blocking | Source |",
      "|-------|----------|----------|--------|",
    ];

    for (const file of files) {
      try {
        const extraction = parseTasksPhp(file);
        if (!extraction) continue;
        const source = relative(moodlePath, file);
        for (const task of extraction.tasks) {
          lines.push(
            `| \`${task.classname}\` | \`${formatCronSchedule(task)}\` | ${task.blocking ? "✔" : ""} | ${source} |`
          );
        }
      } catch { /* skip */ }
    }

    lines.push("");
    return write(output, lines.join("\n"));
  });
}

export async function generateServicesIndex(moodlePath: string): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_SERVICES_INDEX.md");

  return safely(output, async () => {
    const files = await glob("**/db/services.php", {
      cwd: moodlePath, absolute: true,
      ignore: ["vendor/**", "node_modules/**"],
    });

    const lines = [
      header("Moodle Services Index", "All web service functions registered across all plugins."),
      `Sources scanned: **${files.length}** services.php files`,
      "",
      "---",
      "",
      "| Function | Type | AJAX | Class | Source |",
      "|----------|------|------|-------|--------|",
    ];

    for (const file of files) {
      try {
        const extraction = parseServicesPhp(file);
        if (!extraction) continue;
        const source = relative(moodlePath, file);
        for (const fn of extraction.functions) {
          lines.push(
            `| \`${fn.name}\` | ${fn.type} | ${fn.ajax ? "✔" : ""} | \`${fn.classname}\` | ${source} |`
          );
        }
      } catch { /* skip */ }
    }

    lines.push("");
    return write(output, lines.join("\n"));
  });
}

export async function generateDbTablesIndex(moodlePath: string): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_DB_TABLES_INDEX.md");

  return safely(output, async () => {
    const files = await glob("**/db/install.xml", {
      cwd: moodlePath, absolute: true,
      ignore: ["vendor/**", "node_modules/**"],
    });

    const lines = [
      header("Moodle Database Tables Index", "All database tables defined across all plugins."),
      `Sources scanned: **${files.length}** install.xml files`,
      "",
      "---",
      "",
      "| Table | Fields | Source |",
      "|-------|--------|--------|",
    ];

    for (const file of files) {
      try {
        const schema = parseInstallXml(file);
        if (!schema) continue;
        const source = relative(moodlePath, file);
        for (const table of schema.tables) {
          lines.push(`| \`${table.name}\` | ${table.fields.length} | ${source} |`);
        }
      } catch { /* skip */ }
    }

    lines.push("");
    return write(output, lines.join("\n"));
  });
}

export async function generateClassesIndex(moodlePath: string): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_CLASSES_INDEX.md");

  return safely(output, async () => {
    const extraction = await extractClasses(moodlePath, moodlePath);

    const lines = [
      header("Moodle Classes Index", "All PHP classes, interfaces, traits and enums."),
      `Total: **${extraction.classes.length}** class-like declarations`,
      "",
      "---",
      "",
      "| FQN | Kind | File |",
      "|-----|------|------|",
      ...extraction.classes.map((cls) => `| \`${cls.fqn}\` | ${cls.kind} | ${cls.file} |`),
      "",
    ];

    return write(output, lines.join("\n"));
  });
}

export async function generateCapabilitiesIndex(moodlePath: string): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_CAPABILITIES_INDEX.md");

  return safely(output, async () => {
    const files = await glob("**/db/access.php", {
      cwd: moodlePath, absolute: true,
      ignore: ["vendor/**", "node_modules/**"],
    });

    const lines = [
      header("Moodle Capabilities Index", "All capabilities defined across all plugins."),
      `Sources scanned: **${files.length}** access.php files`,
      "",
      "---",
      "",
      "| Capability | Type | Context | Source |",
      "|------------|------|---------|--------|",
    ];

    for (const file of files) {
      try {
        const extraction = parseAccessPhp(file);
        if (!extraction) continue;
        const source = relative(moodlePath, file);
        for (const cap of extraction.capabilities) {
          lines.push(`| \`${cap.name}\` | ${cap.captype} | ${cap.contextlevel} | ${source} |`);
        }
      } catch { /* skip */ }
    }

    lines.push("");
    return write(output, lines.join("\n"));
  });
}

export async function generatePluginIndex(moodlePath: string): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_PLUGIN_INDEX.md");

  return safely(output, async () => {
    const pluginDirs = await findPluginDirs(moodlePath);

    const lines = [
      header("Moodle Plugin Index", "All plugins detected in this Moodle installation."),
      `Total plugins: **${pluginDirs.length}**`,
      "",
      "---",
      "",
      "| Component | Type | Name | Version | Path |",
      "|-----------|------|------|---------|------|",
    ];

    for (const pluginDir of pluginDirs.sort()) {
      try {
        const info = detectPlugin(pluginDir);
        const rel  = relative(moodlePath, pluginDir);
        lines.push(
          `| \`${info.component}\` | ${info.type} | ${info.displayName || info.name} | ${info.version} | ${rel} |`
        );
      } catch { /* skip */ }
    }

    lines.push("");
    return write(output, lines.join("\n"));
  });
}

export function generateDevRules(moodlePath: string): GeneratorResult {
  const output = join(moodlePath, "MOODLE_DEV_RULES.md");

  try {
    const content = [
      header("Moodle Development Rules", "Coding standards and best practices for Moodle plugin development."),
      "## Coding Standards",
      "",
      "- Follow [Moodle Coding Style](https://docs.moodle.org/dev/Coding_style)",
      "- 4-space indentation, no tabs",
      "- Opening braces on same line for control structures",
      "- PHPDoc on all functions and classes",
      "- Snake_case for functions and variables",
      "- PascalCase for class names",
      "",
      "## Security",
      "",
      "Always call at the top of every page script:",
      "```php",
      "require_login($course, true, $cm);",
      "require_capability('local/myplugin:view', $context);",
      "```",
      "",
      "Validate all input parameters:",
      "```php",
      "$id   = required_param('id', PARAM_INT);",
      "$name = optional_param('name', '', PARAM_TEXT);",
      "```",
      "",
      "Escape all output:",
      "```php",
      "echo $OUTPUT->header();",
      "echo format_string($name);",
      "echo format_text($description);",
      "echo s($value);",
      "```",
      "",
      "## Database",
      "",
      "Use the `$DB` global — never raw PDO or mysqli:",
      "```php",
      "$record  = $DB->get_record('table', ['id' => $id], '*', MUST_EXIST);",
      "$records = $DB->get_records('table', ['courseid' => $courseid]);",
      "$DB->insert_record('table', $record);",
      "$DB->update_record('table', $record);",
      "$DB->delete_records('table', ['id' => $id]);",
      "```",
      "",
      "## Plugin File Structure",
      "",
      "```",
      "myplugin/",
      "├── db/",
      "│   ├── install.xml",
      "│   ├── access.php",
      "│   ├── events.php",
      "│   ├── tasks.php",
      "│   └── services.php",
      "├── classes/",
      "├── lang/en/",
      "├── lib.php",
      "├── version.php",
      "└── settings.php",
      "```",
      "",
      "## Events",
      "",
      "```php",
      "$event = \\local_myplugin\\event\\something_happened::create([",
      "    'context'  => $context,",
      "    'objectid' => $record->id,",
      "]);",
      "$event->trigger();",
      "```",
      "",
      "## Scheduled Tasks",
      "",
      "```php",
      "class my_task extends \\core\\task\\scheduled_task {",
      "    public function get_name() { return get_string('mytask', 'local_myplugin'); }",
      "    public function execute() { /* ... */ }",
      "}",
      "```",
      "",
    ].join("\n");

    return write(output, content);
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

export function generatePluginGuide(moodlePath: string, moodleVersion: string): GeneratorResult {
  const output = join(moodlePath, "MOODLE_PLUGIN_GUIDE.md");

  try {
    const content = [
      header("Moodle Plugin Development Guide", `Quick reference for Moodle ${moodleVersion} plugin development.`),
      "## Component Naming",
      "",
      "Format: `{type}_{name}`",
      "",
      "| Type | Directory | Example |",
      "|------|-----------|---------|",
      "| `mod`   | `mod/`           | `mod_quiz` |",
      "| `local` | `local/`         | `local_mytools` |",
      "| `block` | `blocks/`        | `block_navigation` |",
      "| `tool`  | `admin/tool/`    | `tool_upgrade` |",
      "| `auth`  | `auth/`          | `auth_oauth2` |",
      "| `enrol` | `enrol/`         | `enrol_manual` |",
      "| `theme` | `theme/`         | `theme_boost` |",
      "| `report`| `report/`        | `report_log` |",
      "| `format`| `course/format/` | `format_topics` |",
      "",
      "## Required Files",
      "",
      "| File | Required | Purpose |",
      "|------|----------|---------|",
      "| `version.php`             | ✔ | Plugin metadata |",
      "| `lang/en/{component}.php` | ✔ | Language strings |",
      "| `db/install.xml`          |   | DB tables |",
      "| `db/access.php`           |   | Capabilities |",
      "| `lib.php`                 |   | Hook callbacks |",
      "| `settings.php`            |   | Admin settings |",
      "",
      "## version.php Template",
      "",
      "```php",
      "<?php",
      "defined('MOODLE_INTERNAL') || die();",
      "",
      "$plugin->component = 'local_myplugin';",
      "$plugin->version   = 2024010100;",
      "$plugin->requires  = 2022112800;",
      "$plugin->maturity  = MATURITY_STABLE;",
      "$plugin->release   = '1.0.0';",
      "```",
      "",
      "## Autoloaded Classes",
      "",
      "```",
      "classes/output/renderer.php  →  \\local_myplugin\\output\\renderer",
      "classes/task/my_task.php     →  \\local_myplugin\\task\\my_task",
      "classes/external/get_data.php → \\local_myplugin\\external\\get_data",
      "```",
      "",
    ].join("\n");

    return write(output, content);
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

export async function generateAiWorkspace(
  moodlePath: string,
  moodleVersion: string
): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_AI_WORKSPACE.md");

  return safely(output, async () => {
    const pluginDirs = await findPluginDirs(moodlePath);

    const devPlugins = pluginDirs.filter((p) =>
      existsSync(join(p, ".moodle-mcp-dev"))
    );
    const aiPlugins = pluginDirs.filter((p) =>
      existsSync(join(p, "PLUGIN_AI_CONTEXT.md"))
    );

    const lines = [
      header("Moodle AI Workspace", "Workspace configuration and navigation guide for AI assistants."),
      "## Moodle Installation",
      "",
      "| Property | Value |",
      "|----------|-------|",
      `| Version  | ${moodleVersion} |`,
      `| Path     | ${moodlePath} |`,
      `| Total plugins   | ${pluginDirs.length} |`,
      `| Dev plugins     | ${devPlugins.length} |`,
      `| Plugins with AI context | ${aiPlugins.length} |`,
      "",
      "---",
      "",
      "## How to Use This Workspace",
      "",
      "1. Start with **AI_CONTEXT.md** for a general overview",
      "2. Use **MOODLE_PLUGIN_INDEX.md** to find available plugins",
      "3. Open **PLUGIN_AI_CONTEXT.md** inside a plugin for focused context",
      "4. Check **MOODLE_API_INDEX.md** to find available Moodle functions",
      "5. Use **MOODLE_DB_TABLES_INDEX.md** to understand the data model",
      "",
      "---",
      "",
    ];

    if (devPlugins.length > 0) {
      lines.push("## Plugins In Development", "");
      lines.push("| Component | Path |");
      lines.push("|-----------|------|");
      for (const p of devPlugins) {
        try {
          const info = detectPlugin(p);
          const rel  = relative(moodlePath, p);
          lines.push(`| \`${info.component}\` | ${rel} |`);
        } catch { /* skip */ }
      }
      lines.push("", "---", "");
    }

    if (aiPlugins.length > 0) {
      lines.push("## Plugins With AI Context", "");
      lines.push("| Component | AI Context File |");
      lines.push("|-----------|-----------------|");
      for (const p of aiPlugins) {
        try {
          const info = detectPlugin(p);
          const rel  = relative(moodlePath, p);
          lines.push(`| \`${info.component}\` | [PLUGIN_AI_CONTEXT.md](${rel}/PLUGIN_AI_CONTEXT.md) |`);
        } catch { /* skip */ }
      }
      lines.push("");
    }

    return write(output, lines.join("\n"));
  });
}

export async function generateAiIndex(
  moodlePath: string,
  moodleVersion: string
): Promise<GeneratorResult> {
  const output = join(moodlePath, "MOODLE_AI_INDEX.md");

  return safely(output, async () => {
    const pluginDirs = await findPluginDirs(moodlePath);
    const aiPlugins  = pluginDirs.filter((p) =>
      existsSync(join(p, "PLUGIN_AI_CONTEXT.md"))
    );

    const globalFiles = [
      ["AI_CONTEXT.md",                "Installation overview"],
      ["MOODLE_AI_WORKSPACE.md",       "AI workspace guide"],
      ["MOODLE_API_INDEX.md",          "Core API functions"],
      ["MOODLE_EVENTS_INDEX.md",       "Event observers"],
      ["MOODLE_TASKS_INDEX.md",        "Scheduled tasks"],
      ["MOODLE_SERVICES_INDEX.md",     "Web service functions"],
      ["MOODLE_DB_TABLES_INDEX.md",    "Database tables"],
      ["MOODLE_CLASSES_INDEX.md",      "PHP classes"],
      ["MOODLE_CAPABILITIES_INDEX.md", "Capabilities"],
      ["MOODLE_PLUGIN_INDEX.md",       "Plugin map"],
      ["MOODLE_DEV_RULES.md",          "Coding standards"],
      ["MOODLE_PLUGIN_GUIDE.md",       "Plugin development guide"],
    ];

    const lines = [
      header("Moodle AI Index", `Master index. Moodle ${moodleVersion} — ${moodlePath}`),
      "## Global Context Files",
      "",
    ];

    for (const [file, desc] of globalFiles) {
      if (existsSync(join(moodlePath, file))) {
        lines.push(`- [${file}](${file}) — ${desc}`);
      }
    }

    lines.push("", "---", "");

    if (aiPlugins.length > 0) {
      lines.push("## Plugin AI Contexts", "");
      for (const p of aiPlugins.sort()) {
        try {
          const info = detectPlugin(p);
          const rel  = relative(moodlePath, p);
          lines.push(`- [\`${info.component}\`](${rel}/PLUGIN_AI_CONTEXT.md) — ${info.displayName || info.name}`);
        } catch { /* skip */ }
      }
      lines.push("");
    }

    return write(output, lines.join("\n"));
  });
}

/**
 * Generates a ctags file for the Moodle installation.
 * Skipped gracefully when ctags is not available.
 */
export function generateCtags(moodlePath: string): GeneratorResult {
  const output = join(moodlePath, "tags");

  try {
    execSync("command -v ctags", { stdio: "ignore" });
  } catch {
    return { file: output, success: false, error: "ctags not found — skipped" };
  }

  try {
    execSync(
      `ctags -R --languages=PHP --exclude=vendor --exclude=node_modules -f "${output}" "${moodlePath}"`,
      { stdio: "ignore", timeout: 120_000 }
    );
    globalCache.mark(output);
    return { file: output, success: true };
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

export async function generateAll(
  moodlePath: string,
  moodleVersion: string
): Promise<GeneratorResult[]> {
  const results: GeneratorResult[] = [];

  const sources = getMoodleSourcePatterns(moodlePath);

  // Helper: skip if cache says output is fresh
  async function run(
    outputFile: string,
    fn: () => Promise<GeneratorResult> | GeneratorResult
  ): Promise<void> {
    if (!globalCache.isStale(outputFile, sources)) {
      results.push({ file: outputFile, success: true, skipped: true });
      return;
    }
    results.push(await fn());
  }

  await run(join(moodlePath, "AI_CONTEXT.md"),
    () => generateAiContext(moodlePath, moodleVersion));
  await run(join(moodlePath, "MOODLE_API_INDEX.md"),
    () => generateApiIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_EVENTS_INDEX.md"),
    () => generateEventsIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_TASKS_INDEX.md"),
    () => generateTasksIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_SERVICES_INDEX.md"),
    () => generateServicesIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_DB_TABLES_INDEX.md"),
    () => generateDbTablesIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_CLASSES_INDEX.md"),
    () => generateClassesIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_CAPABILITIES_INDEX.md"),
    () => generateCapabilitiesIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_PLUGIN_INDEX.md"),
    () => generatePluginIndex(moodlePath));
  await run(join(moodlePath, "MOODLE_DEV_RULES.md"),
    () => generateDevRules(moodlePath));
  await run(join(moodlePath, "MOODLE_PLUGIN_GUIDE.md"),
    () => generatePluginGuide(moodlePath, moodleVersion));
  await run(join(moodlePath, "MOODLE_AI_WORKSPACE.md"),
    () => generateAiWorkspace(moodlePath, moodleVersion));
  await run(join(moodlePath, "MOODLE_AI_INDEX.md"),
    () => generateAiIndex(moodlePath, moodleVersion));

  results.push(generateCtags(moodlePath));

  return results;
}
