/**
 * @file generators/plugin.ts
 * @description Generates per-plugin AI context markdown files.
 *
 * Improvements over initial version:
 *   - All paths in generated .md are relative to moodlePath
 *   - PLUGIN_STRUCTURE.md filters out moodle-mcp generated files
 *   - Every generator wrapped in try/catch error boundary
 *   - Cache integration via globalCache
 *   - db/upgrade.php extracted and included in PLUGIN_DEPENDENCIES.md
 *   - All output messages in English
 */

import { writeFileSync, existsSync, readdirSync, statSync, readFileSync } from "fs";
import { join, relative }                                                  from "path";
import { glob }                                                            from "glob";

import { detectPlugin, PluginInfo }                                        from "../extractors/plugin.js";
import { extractPluginSchema, tableToMarkdown }                            from "../extractors/schema.js";
import { extractPluginEvents }                                             from "../extractors/events.js";
import { extractPluginTasks, formatCronSchedule }                          from "../extractors/tasks.js";
import { extractPluginServices }                                           from "../extractors/services.js";
import { extractPluginCapabilities }                                       from "../extractors/capabilities.js";
import { extractPluginClasses }                                            from "../extractors/classes.js";
import { extractPluginUpgrade }                                            from "../extractors/upgrade.js";
import { extractPluginHooks, pluginUsesHookApi } from "../extractors/hooks.js";
import { globalCache, getPluginSourceFiles }                               from "../cache.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PluginGeneratorResult {
  plugin: string;
  files:  Array<{ file: string; success: boolean; error?: string; skipped?: boolean }>;
}

// ---------------------------------------------------------------------------
// Constants — files generated by moodle-mcp (filtered from PLUGIN_STRUCTURE)
// ---------------------------------------------------------------------------

const GENERATED_FILES = new Set([
  "PLUGIN_AI_CONTEXT.md",
  "PLUGIN_CONTEXT.md",
  "PLUGIN_STRUCTURE.md",
  "PLUGIN_DB_TABLES.md",
  "PLUGIN_EVENTS.md",
  "PLUGIN_DEPENDENCIES.md",
  "PLUGIN_ARCHITECTURE.md",
  "PLUGIN_FUNCTION_INDEX.md",
  "PLUGIN_CALLBACK_INDEX.md",
  "PLUGIN_ENDPOINT_INDEX.md",
  "PLUGIN_RUNTIME_FLOW.md",
  ".moodle-mcp-dev",
]);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type FileResult = { file: string; success: boolean; error?: string; skipped?: boolean };

function write(filePath: string, content: string): FileResult {
  try {
    writeFileSync(filePath, content, "utf-8");
    globalCache.mark(filePath);
    return { file: filePath, success: true };
  } catch (e) {
    return { file: filePath, success: false, error: String(e) };
  }
}

function timestamp(): string {
  return new Date().toISOString().replace("T", " ").substring(0, 19);
}

function header(title: string, description: string): string {
  return [
    `# ${title}`,
    "",
    `> ${description}`,
    "",
    `_Generated by moodle-mcp on ${timestamp()}_`,
    "",
    "---",
    "",
  ].join("\n");
}

async function safely(
  outputFile: string,
  fn: () => Promise<FileResult>
): Promise<FileResult> {
  try {
    return await fn();
  } catch (e) {
    return { file: outputFile, success: false, error: String(e) };
  }
}

/**
 * Builds a directory tree string, filtering generated files at depth 0.
 */
function buildDirectoryTree(dirPath: string, prefix = "", depth = 0): string {
  if (depth > 2) return "";

  const lines: string[] = [];
  let entries: string[] = [];

  try {
    entries = readdirSync(dirPath).filter((e) => {
      if (e.startsWith(".")) return false;
      if (e === "node_modules" || e === "vendor") return false;
      // Filter moodle-mcp generated files at root level only
      if (depth === 0 && GENERATED_FILES.has(e)) return false;
      return true;
    });
  } catch {
    return "";
  }

  entries.sort((a, b) => {
    const aIsDir = statSync(join(dirPath, a)).isDirectory();
    const bIsDir = statSync(join(dirPath, b)).isDirectory();
    if (aIsDir && !bIsDir) return -1;
    if (!aIsDir && bIsDir) return 1;
    return a.localeCompare(b);
  });

  for (let i = 0; i < entries.length; i++) {
    const entry    = entries[i];
    const isLast   = i === entries.length - 1;
    const pointer  = isLast ? "└── " : "├── ";
    const fullPath = join(dirPath, entry);
    const isDir    = statSync(fullPath).isDirectory();

    lines.push(`${prefix}${pointer}${entry}${isDir ? "/" : ""}`);

    if (isDir) {
      const ext = isLast ? "    " : "│   ";
      const sub = buildDirectoryTree(fullPath, prefix + ext, depth + 1);
      if (sub) lines.push(sub);
    }
  }

  return lines.join("\n");
}

function extractFunctionsFromFile(filePath: string): string[] {
  try {
    const content = readFileSync(filePath, "utf-8");
    const pattern = /^function\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/gm;
    const names: string[] = [];
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(content)) !== null) {
      if (!match[1].startsWith("__")) names.push(match[1]);
    }
    return names;
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// Individual generators
// ---------------------------------------------------------------------------

export function generatePluginContext(info: PluginInfo): FileResult {
  const output = join(info.path, "PLUGIN_CONTEXT.md");

  try {
    const schema       = extractPluginSchema(info.path);
    const events       = extractPluginEvents(info.path);
    const tasks        = extractPluginTasks(info.path);
    const services     = extractPluginServices(info.path);
    const capabilities = extractPluginCapabilities(info.path);

    const content = [
      header(`Plugin Context: ${info.component}`, `Metadata and summary for ${info.displayName || info.name}.`),
      "## Plugin Information",
      "",
      "| Property | Value |",
      "|----------|-------|",
      `| Component    | \`${info.component}\` |`,
      `| Type         | ${info.type} |`,
      `| Name         | ${info.name} |`,
      `| Display Name | ${info.displayName} |`,
      `| Version      | ${info.version} |`,
      `| Requires     | ${info.requires} |`,
      `| Maturity     | ${info.maturity} |`,
      `| Path         | ${info.moodlePath ? relative(info.moodlePath, info.path) : info.path} |`,
      "",
      "---",
      "",
      "## Summary",
      "",
      "| Feature | Count |",
      "|---------|-------|",
      `| DB Tables        | ${schema?.tables.length ?? 0} |`,
      `| Event Observers  | ${events?.observers.length ?? 0} |`,
      `| Scheduled Tasks  | ${tasks?.tasks.length ?? 0} |`,
      `| Web Services     | ${services?.functions.length ?? 0} |`,
      `| Capabilities     | ${capabilities?.capabilities.length ?? 0} |`,
      "",
    ].join("\n");

    return write(output, content);
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

export function generatePluginStructure(info: PluginInfo): FileResult {
  const output = join(info.path, "PLUGIN_STRUCTURE.md");

  try {
    const tree = buildDirectoryTree(info.path);

    const content = [
      header(`Plugin Structure: ${info.component}`, "Directory tree and file inventory."),
      "## Directory Tree",
      "",
      "```",
      `${info.name}/`,
      tree,
      "```",
      "",
      "> Generated files (PLUGIN_*.md, .moodle-mcp-dev) are excluded from the tree.",
      "",
      "---",
      "",
      "## Key Files",
      "",
      "| File | Exists | Purpose |",
      "|------|--------|---------|",
      ...[
        ["version.php",     "Plugin metadata"],
        ["lib.php",         "Hook callbacks"],
        ["locallib.php",    "Internal functions"],
        ["settings.php",    "Admin settings"],
        ["db/install.xml",  "Database tables"],
        ["db/access.php",   "Capabilities"],
        ["db/events.php",   "Event observers"],
        ["db/tasks.php",    "Scheduled tasks"],
        ["db/services.php", "Web services"],
        ["db/upgrade.php",  "DB upgrade steps"],
      ].map(([file, purpose]) => {
        const exists = existsSync(join(info.path, file)) ? "✔" : "";
        return `| \`${file}\` | ${exists} | ${purpose} |`;
      }),
      "",
    ].join("\n");

    return write(output, content);
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

export function generatePluginDbTables(info: PluginInfo): FileResult {
  const output = join(info.path, "PLUGIN_DB_TABLES.md");

  try {
    const schema = extractPluginSchema(info.path);
    const lines  = [
      header(`Plugin Database Tables: ${info.component}`, "Full database schema including fields, keys and indexes."),
    ];

    if (!schema || schema.tables.length === 0) {
      lines.push("_No database tables defined for this plugin._", "");
    } else {
      lines.push(`Tables defined: **${schema.tables.length}**`, "", "---", "");
      for (const table of schema.tables) {
        lines.push(tableToMarkdown(table));
      }
    }

    return write(output, lines.join("\n"));
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

export function generatePluginEvents(info: PluginInfo): FileResult {
  const output = join(info.path, "PLUGIN_EVENTS.md");

  try {
    const events = extractPluginEvents(info.path);
    const lines  = [
      header(`Plugin Events: ${info.component}`, "Event observers registered by this plugin."),
    ];

    if (!events || events.observers.length === 0) {
      lines.push("_No event observers registered by this plugin._", "");
    } else {
      lines.push(`Observers: **${events.observers.length}**`, "");
      lines.push("| Event | Callback | Priority | Internal |");
      lines.push("|-------|----------|----------|----------|");
      for (const obs of events.observers) {
        lines.push(`| \`${obs.eventname}\` | \`${obs.callback}\` | ${obs.priority} | ${obs.internal ? "✔" : ""} |`);
      }
      lines.push("");
    }

    return write(output, lines.join("\n"));
  } catch (e) {
    return { file: output, success: false, error: String(e) };
  }
}

export async function generatePluginDependencies(info: PluginInfo): Promise<FileResult> {
  const output = join(info.path, "PLUGIN_DEPENDENCIES.md");

  return safely(output, async () => {
    const tasks        = extractPluginTasks(info.path);
    const services     = extractPluginServices(info.path);
    const capabilities = extractPluginCapabilities(info.path);
    const upgrade      = extractPluginUpgrade(info.path);
    const hooks        = await extractPluginHooks(info.path, info.component);

    const lines = [
      header(`Plugin Dependencies: ${info.component}`,
        "Scheduled tasks, web services, capabilities, Hook API callbacks, and upgrade history."),
    ];

    // Tasks
    lines.push("## Scheduled Tasks", "");
    if (!tasks || tasks.tasks.length === 0) {
      lines.push("_No scheduled tasks._");
    } else {
      lines.push("| Class | Schedule | Blocking |");
      lines.push("|-------|----------|----------|");
      for (const task of tasks.tasks) {
        lines.push(`| \`${task.classname}\` | \`${formatCronSchedule(task)}\` | ${task.blocking ? "✔" : ""} |`);
      }
    }
    lines.push("");

    // Services
    lines.push("## Web Services", "");
    if (!services || services.functions.length === 0) {
      lines.push("_No web services._");
    } else {
      lines.push("| Function | Type | AJAX | Description |");
      lines.push("|----------|------|------|-------------|");
      for (const fn of services.functions) {
        lines.push(`| \`${fn.name}\` | ${fn.type} | ${fn.ajax ? "✔" : ""} | ${fn.description} |`);
      }
    }
    lines.push("");

    // Capabilities
    lines.push("## Capabilities", "");
    if (!capabilities || capabilities.capabilities.length === 0) {
      lines.push("_No capabilities defined._");
    } else {
      lines.push("| Capability | Type | Context |");
      lines.push("|------------|------|---------|");
      for (const cap of capabilities.capabilities) {
        lines.push(`| \`${cap.name}\` | ${cap.captype} | ${cap.contextlevel} |`);
      }
    }
    lines.push("");

    // Hook API (Moodle 4.3+)
    lines.push("## Hook API (Moodle 4.3+)", "");

    if (hooks.callbacks.length > 0) {
      lines.push("### Registered Callbacks (db/hooks.php)", "");
      lines.push("| Hook | Callback | Priority |");
      lines.push("|------|----------|----------|");
      for (const cb of hooks.callbacks) {
        lines.push(`| \`${cb.hookname}\` | \`${cb.callback}\` | ${cb.priority} |`);
      }
      lines.push("");
    }

    if (hooks.definitions.length > 0) {
      lines.push("### Hook Definitions (classes/hook/)", "");
      lines.push("| Class | Description | Tags | Replaces |");
      lines.push("|-------|-------------|------|----------|");
      for (const def of hooks.definitions) {
        const tags     = def.tags.join(", ") || "—";
        const replaces = def.replaces ? `\`${def.replaces}\`` : "—";
        lines.push(`| \`${def.classname}\` | ${def.description} | ${tags} | ${replaces} |`);
      }
      lines.push("");
    }

    if (!pluginUsesHookApi(hooks)) {
      lines.push("_This plugin does not use the Hook API._", "");
    }

    // Legacy callback warnings
    if (hooks.legacyWarnings.length > 0) {
      lines.push("### ⚠ Legacy Callbacks — Migration Required", "");
      lines.push(
        "> These lib.php callbacks have been replaced by the Hook API in Moodle 4.3+.",
        "> Migrate them to avoid deprecation warnings.",
        ""
      );
      lines.push("| Legacy Function | Replaced By |");
      lines.push("|-----------------|-------------|");
      for (const warn of hooks.legacyWarnings) {
        lines.push(`| \`${warn.legacyFunction}\` | \`${warn.replacedBy}\` |`);
      }
      lines.push("");
      lines.push("**Migration steps for each:**");
      for (const warn of hooks.legacyWarnings) {
        lines.push(`- \`${warn.legacyFunction}\`: ${warn.guidance}`);
      }
      lines.push("");
    }

    // Upgrade history
    lines.push("## Upgrade History", "");
    if (!upgrade || upgrade.steps.length === 0) {
      lines.push("_No upgrade.php found or no steps defined._");
    } else {
      lines.push(`Steps defined: **${upgrade.steps.length}**`, "");
      lines.push("| Version | Description |");
      lines.push("|---------|-------------|");
      for (const step of upgrade.steps) {
        lines.push(`| ${step.version} | ${step.description || "—"} |`);
      }
    }
    lines.push("");

    return write(output, lines.join("\n"));
  });
}

export async function generatePluginFunctionIndex(info: PluginInfo): Promise<FileResult> {
  const output = join(info.path, "PLUGIN_FUNCTION_INDEX.md");

  return safely(output, async () => {
    const phpFiles = await glob("**/*.php", {
      cwd: info.path, absolute: true,
      ignore: ["vendor/**"],
    });

    const lines = [
      header(`Plugin Function Index: ${info.component}`, "All PHP functions declared in this plugin."),
    ];

    for (const file of phpFiles.sort()) {
      const fns = extractFunctionsFromFile(file);
      if (fns.length === 0) continue;
      const rel = relative(info.path, file);
      lines.push(`## ${rel}`, "");
      for (const fn of fns) lines.push(`- \`${fn}()\``);
      lines.push("");
    }

    return write(output, lines.join("\n"));
  });
}

export async function generatePluginCallbackIndex(info: PluginInfo): Promise<FileResult> {
  const output  = join(info.path, "PLUGIN_CALLBACK_INDEX.md");
  const prefix  = `${info.component}_`;

  return safely(output, async () => {
    const hooks = await extractPluginHooks(info.path, info.component);

    const lines = [
      header(
        `Plugin Callback Index: ${info.component}`,
        "Legacy lib.php callbacks and Hook API (Moodle 4.3+) registrations."
      ),
    ];

    // -----------------------------------------------------------------------
    // Section 1: Legacy lib.php callbacks
    // -----------------------------------------------------------------------
    lines.push("## Legacy Callbacks (lib.php)", "");
    lines.push(
      "> Functions prefixed with `" + prefix + "` in lib.php.",
      "> In Moodle 4.3+, many of these should be migrated to the Hook API.",
      ""
    );

    const filesToCheck = [join(info.path, "lib.php"), join(info.path, "locallib.php")];
    let legacyFound = 0;

    for (const file of filesToCheck) {
      if (!existsSync(file)) continue;
      const fns = extractFunctionsFromFile(file).filter((fn) => fn.startsWith(prefix));
      if (fns.length === 0) continue;

      const rel = relative(info.path, file);
      lines.push(`### ${rel}`, "");
      for (const fn of fns) {
        // Flag functions that have known hook replacements
        const suffix     = fn.replace(prefix, "");
        const hasWarning = hooks.legacyWarnings.some((w) => w.legacyFunction === fn);
        const depr       = hasWarning ? " ⚠ _(has Hook API replacement)_" : "";
        lines.push(`- \`${fn}()\`${depr}`);
      }
      lines.push("");
      legacyFound += fns.length;
    }

    if (legacyFound === 0) {
      lines.push("_No legacy hook callbacks found._", "");
    }

    // -----------------------------------------------------------------------
    // Section 2: Hook API callbacks (Moodle 4.3+)
    // -----------------------------------------------------------------------
    lines.push("## Hook API Callbacks (Moodle 4.3+)", "");

    if (hooks.callbacks.length > 0) {
      lines.push("Registered in `db/hooks.php`:", "");
      lines.push("| Hook | Callback | Priority | Enabled |");
      lines.push("|------|----------|----------|---------|");
      for (const cb of hooks.callbacks) {
        const enabled = cb.defaultenabled ? "✔" : "";
        lines.push(`| \`${cb.hookname}\` | \`${cb.callback}\` | ${cb.priority} | ${enabled} |`);
      }
      lines.push("");
    } else {
      lines.push("_This plugin does not register any Hook API callbacks._", "");
    }

    // -----------------------------------------------------------------------
    // Section 3: Hook definitions
    // -----------------------------------------------------------------------
    if (hooks.definitions.length > 0) {
      lines.push("## Hook Definitions (classes/hook/)", "");
      lines.push("Hooks defined by this plugin that others can listen to:", "");
      for (const def of hooks.definitions) {
        lines.push(`### \`${def.classname}\``);
        if (def.description) lines.push(`> ${def.description}`, "");
        if (def.tags.length > 0) lines.push(`**Tags:** ${def.tags.join(", ")}`, "");
        if (def.replaces)         lines.push(`**Replaces legacy callback:** \`${def.replaces}\``, "");
        lines.push("");
      }
    }

    // -----------------------------------------------------------------------
    // Section 4: Migration warnings
    // -----------------------------------------------------------------------
    if (hooks.legacyWarnings.length > 0) {
      lines.push("## ⚠ Migration Warnings", "");
      lines.push(
        `${hooks.legacyWarnings.length} legacy callback(s) have Hook API replacements available:`,
        ""
      );
      for (const warn of hooks.legacyWarnings) {
        lines.push(`### \`${warn.legacyFunction}\``);
        lines.push(`**Replace with:** \`${warn.replacedBy}\``);
        lines.push(`**Steps:** ${warn.guidance}`, "");
      }
    }

    return write(output, lines.join("\n"));
  });
}

export async function generatePluginEndpointIndex(info: PluginInfo): Promise<FileResult> {
  const output   = join(info.path, "PLUGIN_ENDPOINT_INDEX.md");

  return safely(output, async () => {
    const services = extractPluginServices(info.path);

    const lines = [
      header(`Plugin Endpoint Index: ${info.component}`, "Web services, AJAX endpoints, and AMD modules."),
      "## Web Services",
      "",
    ];

    if (!services || services.functions.length === 0) {
      lines.push("_No web services._", "");
    } else {
      lines.push("| Function | Type | AJAX | Capabilities |");
      lines.push("|----------|------|------|--------------|");
      for (const fn of services.functions) {
        lines.push(`| \`${fn.name}\` | ${fn.type} | ${fn.ajax ? "✔" : ""} | ${fn.capabilities} |`);
      }
      lines.push("");
    }

    const ajaxFiles = await glob("**/ajax.php", { cwd: info.path, absolute: false, maxDepth: 3 });
    lines.push("## AJAX Endpoints", "");
    if (ajaxFiles.length === 0) {
      lines.push("_No ajax.php files found._", "");
    } else {
      for (const f of ajaxFiles) lines.push(`- \`${f}\``);
      lines.push("");
    }

    const amdSrcDir = join(info.path, "amd", "src");
    lines.push("## AMD JavaScript Modules", "");
    if (!existsSync(amdSrcDir)) {
      lines.push("_No AMD modules found._", "");
    } else {
      const jsFiles = await glob("*.js", { cwd: amdSrcDir });
      if (jsFiles.length === 0) {
        lines.push("_No AMD modules found._");
      } else {
        for (const f of jsFiles.sort()) {
          lines.push(`- \`${info.component}/${f.replace(".js", "")}\``);
        }
      }
      lines.push("");
    }

    return write(output, lines.join("\n"));
  });
}

export async function generatePluginRuntimeFlow(info: PluginInfo): Promise<FileResult> {
  const output = join(info.path, "PLUGIN_RUNTIME_FLOW.md");

  return safely(output, async () => {
    const entryPoints   = ["index.php","view.php","edit.php","manage.php","report.php","ajax.php"];
    const foundEntries  = entryPoints.filter((f) => existsSync(join(info.path, f)));
    const classes       = await extractPluginClasses(info.path);
    const events        = extractPluginEvents(info.path);
    const tasks         = extractPluginTasks(info.path);
    const services      = extractPluginServices(info.path);

    const lines = [
      header(`Plugin Runtime Flow: ${info.component}`, "Entry points, execution flow, and runtime components."),
      "## Entry Points",
      "",
    ];

    if (foundEntries.length === 0) {
      lines.push("_No standard entry point files found._");
    } else {
      for (const f of foundEntries) lines.push(`- \`${f}\``);
    }
    lines.push("");

    lines.push("## Core Logic Files", "");
    for (const f of ["lib.php", "locallib.php", "renderer.php"]) {
      if (existsSync(join(info.path, f))) lines.push(`- \`${f}\``);
    }
    lines.push("");

    if (classes.classes.length > 0) {
      lines.push("## Classes", "");
      lines.push("| Class | Kind | File |");
      lines.push("|-------|------|------|");
      for (const cls of classes.classes) {
        lines.push(`| \`${cls.fqn}\` | ${cls.kind} | ${cls.file} |`);
      }
      lines.push("");
    }

    if (events && events.observers.length > 0) {
      lines.push("## Event Observers", "");
      for (const obs of events.observers) {
        lines.push(`- \`${obs.eventname}\` → \`${obs.callback}\``);
      }
      lines.push("");
    }

    if (tasks && tasks.tasks.length > 0) {
      lines.push("## Scheduled Tasks", "");
      for (const task of tasks.tasks) {
        lines.push(`- \`${task.classname}\` (${formatCronSchedule(task)})`);
      }
      lines.push("");
    }

    if (services && services.functions.length > 0) {
      lines.push("## Web Service Functions", "");
      for (const fn of services.functions) {
        lines.push(`- \`${fn.name}\` (${fn.type})`);
      }
      lines.push("");
    }

    return write(output, lines.join("\n"));
  });
}

export async function generatePluginArchitecture(info: PluginInfo): Promise<FileResult> {
  const output  = join(info.path, "PLUGIN_ARCHITECTURE.md");

  return safely(output, async () => {
    const classes = await extractPluginClasses(info.path);
    const byDir: Record<string, typeof classes.classes> = {};

    for (const cls of classes.classes) {
      const dir = cls.file.includes("/") ? cls.file.split("/").slice(0, -1).join("/") : "root";
      if (!byDir[dir]) byDir[dir] = [];
      byDir[dir].push(cls);
    }

    const lines = [
      header(`Plugin Architecture: ${info.component}`, "High-level architecture overview."),
      "## Overview",
      "",
      "| Property | Value |",
      "|----------|-------|",
      `| Component | \`${info.component}\` |`,
      `| Type      | ${info.type} |`,
      `| Version   | ${info.version} |`,
      `| Maturity  | ${info.maturity} |`,
      "",
      "---",
      "",
      "## Class Structure",
      "",
    ];

    if (Object.keys(byDir).length === 0) {
      lines.push("_No autoloaded classes found._", "");
    } else {
      for (const [dir, clsList] of Object.entries(byDir).sort()) {
        lines.push(`### \`classes/${dir}/\``, "");
        for (const cls of clsList) {
          const ext  = cls.extends ? ` extends \`${cls.extends}\`` : "";
          const impl = cls.implements.length > 0
            ? ` implements ${cls.implements.map((i) => `\`${i}\``).join(", ")}`
            : "";
          lines.push(`- **${cls.kind}** \`${cls.name}\`${ext}${impl}`);
        }
        lines.push("");
      }
    }

    lines.push("---", "", "## Design Notes", "", "_Add architectural notes here after initial generation._", "");
    return write(output, lines.join("\n"));
  });
}

export async function generatePluginAiContext(info: PluginInfo): Promise<FileResult> {
  const output = join(info.path, "PLUGIN_AI_CONTEXT.md");

  return safely(output, async () => {
    const schema       = extractPluginSchema(info.path);
    const events       = extractPluginEvents(info.path);
    const tasks        = extractPluginTasks(info.path);
    const services     = extractPluginServices(info.path);
    const capabilities = extractPluginCapabilities(info.path);
    const classes      = await extractPluginClasses(info.path);
    const hooks        = await extractPluginHooks(info.path, info.component);

    const lines = [
      header(`AI Context: ${info.component}`,
        `Complete AI context for ${info.displayName || info.name}. Load this file first.`),
      "## Quick Reference",
      "",
      "| File | Purpose |",
      "|------|---------|",
      "| [PLUGIN_CONTEXT.md](PLUGIN_CONTEXT.md)           | Metadata summary |",
      "| [PLUGIN_STRUCTURE.md](PLUGIN_STRUCTURE.md)       | Directory tree |",
      "| [PLUGIN_ARCHITECTURE.md](PLUGIN_ARCHITECTURE.md) | Architecture overview |",
      "| [PLUGIN_DB_TABLES.md](PLUGIN_DB_TABLES.md)       | Database schema |",
      "| [PLUGIN_EVENTS.md](PLUGIN_EVENTS.md)             | Event observers |",
      "| [PLUGIN_DEPENDENCIES.md](PLUGIN_DEPENDENCIES.md) | Tasks, services, capabilities, hooks, upgrades |",
      "| [PLUGIN_FUNCTION_INDEX.md](PLUGIN_FUNCTION_INDEX.md) | All functions |",
      "| [PLUGIN_CALLBACK_INDEX.md](PLUGIN_CALLBACK_INDEX.md) | Legacy & Hook API callbacks |",
      "| [PLUGIN_ENDPOINT_INDEX.md](PLUGIN_ENDPOINT_INDEX.md) | Web services & AJAX |",
      "| [PLUGIN_RUNTIME_FLOW.md](PLUGIN_RUNTIME_FLOW.md) | Runtime flow |",
      "",
      "---",
      "",
      "## Plugin",
      "",
      `- **Component:** \`${info.component}\``,
      `- **Type:** ${info.type}`,
      `- **Version:** ${info.version}`,
      `- **Path:** \`${info.moodlePath ? relative(info.moodlePath, info.path) : info.path}\``,
      "",
      "---",
      "",
      "## Database",
      "",
      schema && schema.tables.length > 0
        ? schema.tables.map((t) => `- \`${t.name}\` (${t.fields.length} fields)`).join("\n")
        : "_No tables defined._",
      "",
      "---",
      "",
      "## Events",
      "",
      events && events.observers.length > 0
        ? events.observers.map((o) => `- \`${o.eventname}\``).join("\n")
        : "_No event observers._",
      "",
      "---",
      "",
      "## Tasks",
      "",
      tasks && tasks.tasks.length > 0
        ? tasks.tasks.map((t) => `- \`${t.classname}\``).join("\n")
        : "_No scheduled tasks._",
      "",
      "---",
      "",
      "## Web Services",
      "",
      services && services.functions.length > 0
        ? services.functions.map((f) => `- \`${f.name}\` (${f.type})`).join("\n")
        : "_No web services._",
      "",
      "---",
      "",
      "## Capabilities",
      "",
      capabilities && capabilities.capabilities.length > 0
        ? capabilities.capabilities.map((c) => `- \`${c.name}\``).join("\n")
        : "_No capabilities._",
      "",
      "---",
      "",
      "## Hook API (Moodle 4.3+)",
      "",
      hooks.callbacks.length > 0
        ? hooks.callbacks.map((cb) => `- listens to \`${cb.hookname}\``).join("\n")
        : hooks.definitions.length > 0
          ? hooks.definitions.map((d) => `- defines \`${d.classname}\``).join("\n")
          : "_Does not use the Hook API._",
      hooks.legacyWarnings.length > 0
        ? `\n> ⚠ ${hooks.legacyWarnings.length} legacy callback(s) need migration — see PLUGIN_CALLBACK_INDEX.md`
        : "",
      "",
      "---",
      "",
      "## Classes",
      "",
      classes.classes.length > 0
        ? classes.classes.map((c) => `- \`${c.fqn}\` (${c.kind})`).join("\n")
        : "_No autoloaded classes._",
      "",
    ].join("\n");

    return write(output, lines);
  });
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

export async function generateAllForPlugin(
  pluginPath: string,
  moodlePath: string
): Promise<PluginGeneratorResult> {
  const info    = { ...detectPlugin(pluginPath), moodlePath };
  const sources = getPluginSourceFiles(pluginPath);
  const results: FileResult[] = [];

  async function run(
    outputFile: string,
    fn: () => Promise<FileResult> | FileResult
  ): Promise<void> {
    if (!globalCache.isStale(outputFile, sources)) {
      results.push({ file: outputFile, success: true, skipped: true });
      return;
    }
    results.push(await fn());
  }

  await run(join(pluginPath, "PLUGIN_CONTEXT.md"),        () => generatePluginContext(info));
  await run(join(pluginPath, "PLUGIN_STRUCTURE.md"),      () => generatePluginStructure(info));
  await run(join(pluginPath, "PLUGIN_DB_TABLES.md"),      () => generatePluginDbTables(info));
  await run(join(pluginPath, "PLUGIN_EVENTS.md"),         () => generatePluginEvents(info));
  await run(join(pluginPath, "PLUGIN_DEPENDENCIES.md"),   () => generatePluginDependencies(info));
  await run(join(pluginPath, "PLUGIN_CALLBACK_INDEX.md"), () => generatePluginCallbackIndex(info));
  await run(join(pluginPath, "PLUGIN_FUNCTION_INDEX.md"), () => generatePluginFunctionIndex(info));
  await run(join(pluginPath, "PLUGIN_ENDPOINT_INDEX.md"), () => generatePluginEndpointIndex(info));
  await run(join(pluginPath, "PLUGIN_RUNTIME_FLOW.md"),   () => generatePluginRuntimeFlow(info));
  await run(join(pluginPath, "PLUGIN_ARCHITECTURE.md"),   () => generatePluginArchitecture(info));
  await run(join(pluginPath, "PLUGIN_AI_CONTEXT.md"),     () => generatePluginAiContext(info));

  // Mark as dev plugin
  try {
    writeFileSync(join(pluginPath, ".moodle-mcp-dev"), timestamp(), "utf-8");
  } catch { /* non-fatal */ }

  return { plugin: info.component, files: results };
}
